// Seed script for Teacher Jon's iTalki reviews
// Run seedTeacherJonReviews() to import all reviews

import { createReview, getReviewsByTeacher, getTeacherProfileByUsername } from '@/lib/firestore';
import type { Review } from '@/lib/types';

export const italkiReviews: Omit<Review, 'id'>[] = [
  // === PINNED REVIEWS (Teacher's Pick) ===
  {
    studentName: 'Gordon',
    teacherId: '', // Will be set dynamically
    rating: 5,
    comment: "We have been learning with Teacher Jon for over a year. He has well developed teaching materials for students in different levels. He is always focused and energetic. And his class is well structured and interesting, especially young children.",
    createdAt: '2025-06-08',
    pinned: true,
    visible: true,
    imported: true,
    importSource: 'italki',
    tags: ['Structured lessons'],
  },
  {
    studentName: 'Daria Penskaya',
    studentAvatarUrl: 'https://imagesavatar-static01.italki.com/T125800290_Avatar_3.jpg',
    teacherId: '',
    rating: 5,
    comment: "I'm very grateful to Teacher Jon for his brilliant classes. My son 5,3 years old has started English lessons 5 months ago. It is his first experience to communicate with a person not speaking his mother tongue. The materials Teacher Jon provides are diverse, the tasks are always interesting. Teacher Jon has plenty of tricks to keep attention of my active boy and I really appreciate that English day by day becomes an essential part of my son's life.",
    createdAt: '2023-01-05',
    pinned: true,
    visible: true,
    imported: true,
    importSource: 'italki',
    tags: ['Provides materials', 'For beginners'],
  },
  {
    studentName: 'Luciana Mendes',
    studentAvatarUrl: 'https://imagesavatar-static01.italki.com/T039284620_Avatar_3.jpg',
    teacherId: '',
    rating: 5,
    comment: "Best teacher ever! Jon has an incredible empathy and didactic with children. My son loves taking classes with him. Lots of thanks, Jon!",
    createdAt: '2024-06-05',
    pinned: true,
    visible: true,
    imported: true,
    importSource: 'italki',
    tags: ['For beginners'],
  },
  
  // === REGULAR REVIEWS (newest first) ===
  {
    studentName: 'Iris',
    studentAvatarUrl: 'https://imagesavatar-static01.italki.com/T151365610_Avatar_3.jpg',
    teacherId: '',
    rating: 5,
    comment: "very good teacher for kid",
    createdAt: '2025-11-22',
    pinned: false,
    visible: true,
    imported: true,
    importSource: 'italki',
  },
  {
    studentName: 'Angela',
    teacherId: '',
    rating: 5,
    comment: "老师有自己的课程体系，孩子跟着学习进步很多。课程非常有趣，老师很用心，很专业。",
    createdAt: '2025-12-03',
    pinned: false,
    visible: true,
    imported: true,
    importSource: 'italki',
    tags: ['Structured lessons'],
  },
  {
    studentName: 'Angela',
    teacherId: '',
    rating: 5,
    comment: "Jon老师非常负责，很幸运遇到Jon老师。",
    createdAt: '2025-08-06',
    pinned: false,
    visible: true,
    imported: true,
    importSource: 'italki',
  },
  {
    studentName: 'Max',
    teacherId: '',
    rating: 5,
    comment: "good",
    createdAt: '2025-07-13',
    pinned: false,
    visible: true,
    imported: true,
    importSource: 'italki',
  },
  {
    studentName: 'Max',
    teacherId: '',
    rating: 5,
    comment: "great",
    createdAt: '2025-07-13',
    pinned: false,
    visible: true,
    imported: true,
    importSource: 'italki',
  },
  {
    studentName: 'Max',
    teacherId: '',
    rating: 5,
    comment: "在课堂上，我们不仅学到了知识，更激发了兴趣与创造力。每一次尝试都是一种成长，每一次互动都是一次洗礼。让课堂成为知识的海洋，让学习成为一种享受。",
    createdAt: '2025-07-09',
    pinned: false,
    visible: true,
    imported: true,
    importSource: 'italki',
  },
  {
    studentName: 'Max',
    teacherId: '',
    rating: 5,
    comment: "happy class",
    createdAt: '2025-07-08',
    pinned: false,
    visible: true,
    imported: true,
    importSource: 'italki',
  },
  {
    studentName: 'Joy',
    teacherId: '',
    rating: 5,
    comment: "Teacher Jon teaches with passion. My son like this teacher the best for sure. I recommend!",
    createdAt: '2025-03-12',
    pinned: false,
    visible: true,
    imported: true,
    importSource: 'italki',
  },
  {
    studentName: 'Angela',
    teacherId: '',
    rating: 5,
    comment: "很喜欢上Jon老师的话课，非常有趣。Jon老师很用心，教材成体系，有设计。希望一直跟随Jon老师学习。",
    createdAt: '2025-01-19',
    pinned: false,
    visible: true,
    imported: true,
    importSource: 'italki',
    tags: ['Provides materials'],
  },
  {
    studentName: 'Danny',
    teacherId: '',
    rating: 5,
    comment: "very impressive class",
    createdAt: '2025-01-20',
    pinned: false,
    visible: true,
    imported: true,
    importSource: 'italki',
  },
  {
    studentName: 'Tristan',
    teacherId: '',
    rating: 5,
    comment: "Jon is a good teacher. His class is interesting, my kid likes the customized lesson!",
    createdAt: '2024-12-18',
    pinned: false,
    visible: true,
    imported: true,
    importSource: 'italki',
  },
  {
    studentName: 'Ray',
    teacherId: '',
    rating: 5,
    comment: "well done",
    createdAt: '2024-07-20',
    pinned: false,
    visible: true,
    imported: true,
    importSource: 'italki',
  },
  {
    studentName: 'Oscar Klinger',
    teacherId: '',
    rating: 5,
    comment: "Good experience, good theacher",
    createdAt: '2024-06-18',
    pinned: false,
    visible: true,
    imported: true,
    importSource: 'italki',
  },
  {
    studentName: 'D.V.',
    teacherId: '',
    rating: 5,
    comment: "Jon tiene una estructura muy clara, segura y organizada de su forma de dar las clases. Me gusta.",
    createdAt: '2024-06-08',
    pinned: false,
    visible: true,
    imported: true,
    importSource: 'italki',
    tags: ['Structured lessons'],
  },
  {
    studentName: 'Jeffery LIU',
    teacherId: '',
    rating: 5,
    comment: "It's a very interesting class. Teacher Jon is full of passion!",
    createdAt: '2024-05-29',
    pinned: false,
    visible: true,
    imported: true,
    importSource: 'italki',
  },
  {
    studentName: 'Troy',
    teacherId: '',
    rating: 5,
    comment: "Jon is the best teacher I have ever met! He is energetic all the time and pays lots of attention to kid's reaction. He change his class style according to kid's reaction.",
    createdAt: '2024-05-03',
    pinned: false,
    visible: true,
    imported: true,
    importSource: 'italki',
  },
  {
    studentName: 'mia',
    teacherId: '',
    rating: 5,
    comment: "非常有趣",
    createdAt: '2024-04-27',
    pinned: false,
    visible: true,
    imported: true,
    importSource: 'italki',
  },
  {
    studentName: 'peterls',
    teacherId: '',
    rating: 5,
    comment: "Great professional who really knows how to get the kid's attention.",
    createdAt: '2024-03-31',
    pinned: false,
    visible: true,
    imported: true,
    importSource: 'italki',
  },
  {
    studentName: 'Gabriel',
    teacherId: '',
    rating: 5,
    comment: "Jon is an excellent teacher, he's very attentive and uses cool visual effects and games to keep kids engaged.",
    createdAt: '2024-02-09',
    pinned: false,
    visible: true,
    imported: true,
    importSource: 'italki',
  },
  {
    studentName: 'Artem M',
    teacherId: '',
    rating: 5,
    comment: "Jon is very good teacher",
    createdAt: '2024-02-10',
    pinned: false,
    visible: true,
    imported: true,
    importSource: 'italki',
  },
  {
    studentName: 'bbjauni1010',
    teacherId: '',
    rating: 5,
    comment: "the class was great :)",
    createdAt: '2024-02-07',
    pinned: false,
    visible: true,
    imported: true,
    importSource: 'italki',
  },
  {
    studentName: 'eric',
    teacherId: '',
    rating: 5,
    comment: "nice class. full of interesting materials to engage kids!",
    createdAt: '2023-12-05',
    pinned: false,
    visible: true,
    imported: true,
    importSource: 'italki',
    tags: ['Provides materials'],
  },
  {
    studentName: 'jude-7years-old',
    teacherId: '',
    rating: 5,
    comment: "great, thanks!",
    createdAt: '2023-10-26',
    pinned: false,
    visible: true,
    imported: true,
    importSource: 'italki',
  },
  {
    studentName: 'TTY',
    teacherId: '',
    rating: 5,
    comment: "Wonderful! Thank you very much!",
    createdAt: '2023-10-27',
    pinned: false,
    visible: true,
    imported: true,
    importSource: 'italki',
  },
  {
    studentName: 'Benjamin',
    teacherId: '',
    rating: 5,
    comment: "Jon的课程非常活泼有趣，小朋友很投入，进步很明显",
    createdAt: '2023-10-16',
    pinned: false,
    visible: true,
    imported: true,
    importSource: 'italki',
    tags: ['For beginners'],
  },
  {
    studentName: 'petros',
    teacherId: '',
    rating: 5,
    comment: "my son enjoyed his class so much.teacher john has many materials to teach and it's very fun.for sure,my son will join his class again.thanks teacher john",
    createdAt: '2023-09-15',
    pinned: false,
    visible: true,
    imported: true,
    importSource: 'italki',
    tags: ['Provides materials'],
  },
  {
    studentName: "Zoé's39 and King's11",
    teacherId: '',
    rating: 5,
    comment: "It's crucial to practice speaking skills in the language learning. My kid is a little bit timid but Teacher Jon is good at activating class atmosphere and make him be willing to speak👍",
    createdAt: '2023-09-12',
    pinned: false,
    visible: true,
    imported: true,
    importSource: 'italki',
    tags: ['For beginners'],
  },
  {
    studentName: 'jude-7years-old',
    teacherId: '',
    rating: 5,
    comment: "Jon is a really great teacher, deserve all your respect! and my boy love him. Thanks a lot to Jon.",
    createdAt: '2023-08-10',
    pinned: false,
    visible: true,
    imported: true,
    importSource: 'italki',
  },
  {
    studentName: 'LUCY',
    teacherId: '',
    rating: 5,
    comment: "Great and enjoyble lesson! :)",
    createdAt: '2023-07-31',
    pinned: false,
    visible: true,
    imported: true,
    importSource: 'italki',
  },
  {
    studentName: 'jude-7years-old',
    teacherId: '',
    rating: 5,
    comment: "good.",
    createdAt: '2023-07-07',
    pinned: false,
    visible: true,
    imported: true,
    importSource: 'italki',
  },
  {
    studentName: 'italki730533',
    teacherId: '',
    rating: 5,
    comment: "nice! good for kids",
    createdAt: '2023-07-05',
    pinned: false,
    visible: true,
    imported: true,
    importSource: 'italki',
    tags: ['For beginners'],
  },
  {
    studentName: 'pipipipi',
    teacherId: '',
    rating: 5,
    comment: "Nice teacher! interesting content!",
    createdAt: '2023-07-03',
    pinned: false,
    visible: true,
    imported: true,
    importSource: 'italki',
  },
  {
    studentName: 'jude-7years-old',
    teacherId: '',
    rating: 5,
    comment: "thanks!",
    createdAt: '2023-09-03',
    pinned: false,
    visible: true,
    imported: true,
    importSource: 'italki',
  },
  {
    studentName: 'Rui & Shaun',
    teacherId: '',
    rating: 5,
    comment: "nice teacher",
    createdAt: '2023-05-15',
    pinned: false,
    visible: true,
    imported: true,
    importSource: 'italki',
  },
  {
    studentName: 'TTY',
    teacherId: '',
    rating: 5,
    comment: "Wonderful teacher!",
    createdAt: '2023-04-24',
    pinned: false,
    visible: true,
    imported: true,
    importSource: 'italki',
  },
  {
    studentName: 'Rui & Shaun',
    teacherId: '',
    rating: 5,
    comment: "extraordinarily passionate and skilled teacher with various activities, absolutely stay for more classes.",
    createdAt: '2023-04-21',
    pinned: false,
    visible: true,
    imported: true,
    importSource: 'italki',
  },
  {
    studentName: 'Rui Duan',
    teacherId: '',
    rating: 3,
    comment: "The child is not interested in the topic",
    createdAt: '2023-03-31',
    pinned: false,
    visible: true,
    imported: true,
    importSource: 'italki',
  },
  {
    studentName: 'vonderviszta',
    teacherId: '',
    rating: 5,
    comment: "It was my son's trial lesson. Teacher Jon could make him laugh and at the same time taught him a lot of new things. We are fully satisfied! :)",
    createdAt: '2023-02-03',
    pinned: false,
    visible: true,
    imported: true,
    importSource: 'italki',
    tags: ['For beginners'],
  },
  {
    studentName: 'Rui Duan',
    teacherId: '',
    rating: 5,
    comment: "A kind teacher, Thank you",
    createdAt: '2022-12-27',
    pinned: false,
    visible: true,
    imported: true,
    importSource: 'italki',
  },
  {
    studentName: 'Donna Hu',
    teacherId: '',
    rating: 5,
    comment: "Jon is a wonderful teacher.",
    createdAt: '2022-11-30',
    pinned: false,
    visible: true,
    imported: true,
    importSource: 'italki',
  },
  {
    studentName: 'Donna Hu',
    teacherId: '',
    rating: 5,
    comment: "Jon is always active and enthusiastic in class",
    createdAt: '2022-11-25',
    pinned: false,
    visible: true,
    imported: true,
    importSource: 'italki',
  },
  {
    studentName: 'Donna Hu',
    teacherId: '',
    rating: 5,
    comment: "Jon is flexible in assigning homework, and my daughter likes it much.",
    createdAt: '2022-11-17',
    pinned: false,
    visible: true,
    imported: true,
    importSource: 'italki',
  },
  {
    studentName: 'Donna Hu',
    teacherId: '',
    rating: 5,
    comment: "Joe is always good at intriguing my daughter's interest.",
    createdAt: '2022-11-09',
    pinned: false,
    visible: true,
    imported: true,
    importSource: 'italki',
  },
  {
    studentName: 'Van Simonetto',
    teacherId: '',
    rating: 5,
    comment: "The best teacher so far. my boy just loved him!",
    createdAt: '2022-10-08',
    pinned: false,
    visible: true,
    imported: true,
    importSource: 'italki',
  },
  {
    studentName: 'Tingting',
    teacherId: '',
    rating: 5,
    comment: "Jon is a very patient and funny teacher. He keeps the pace of the class well. Looking forward to our next lesson.",
    createdAt: '2022-10-06',
    pinned: false,
    visible: true,
    imported: true,
    importSource: 'italki',
    tags: ['For beginners'],
  },
  {
    studentName: 'Aris',
    teacherId: '',
    rating: 5,
    comment: "Jon's class is very interesting.",
    createdAt: '2022-09-28',
    pinned: false,
    visible: true,
    imported: true,
    importSource: 'italki',
  },
  {
    studentName: 'Ekaterina Strukova',
    teacherId: '',
    rating: 5,
    comment: "Great lesson",
    createdAt: '2022-09-23',
    pinned: false,
    visible: true,
    imported: true,
    importSource: 'italki',
  },
  {
    studentName: 'Daria Penskaya',
    studentAvatarUrl: 'https://imagesavatar-static01.italki.com/T125800290_Avatar_3.jpg',
    teacherId: '',
    rating: 5,
    comment: "The trial lesson was very good. My son 4,10 really liked all the materials by Teacher Jon and all the different interactive tools that he uses in the class. For my son it was the first time to communicate with a native speaker and he stays very enthusiastic.",
    createdAt: '2022-09-20',
    pinned: false,
    visible: true,
    imported: true,
    importSource: 'italki',
    tags: ['For beginners'],
  },
  {
    studentName: 'Chris',
    teacherId: '',
    rating: 5,
    comment: "My kid lovesssss Teacher John's class!!",
    createdAt: '2022-09-08',
    pinned: false,
    visible: true,
    imported: true,
    importSource: 'italki',
  },
  {
    studentName: 'Ekaterina Strukova',
    teacherId: '',
    rating: 5,
    comment: "Great lesson! Thank you!",
    createdAt: '2022-08-31',
    pinned: false,
    visible: true,
    imported: true,
    importSource: 'italki',
  },
  {
    studentName: 'Donna Hu',
    teacherId: '',
    rating: 5,
    comment: "Jon is good at assigning interesting homework.",
    createdAt: '2022-08-26',
    pinned: false,
    visible: true,
    imported: true,
    importSource: 'italki',
  },
  {
    studentName: 'Donna Hu',
    teacherId: '',
    rating: 5,
    comment: "Jon is a very reliable teacher.",
    createdAt: '2022-08-18',
    pinned: false,
    visible: true,
    imported: true,
    importSource: 'italki',
  },
  {
    studentName: 'Ekaterina Strukova',
    teacherId: '',
    rating: 5,
    comment: "Great lesson!",
    createdAt: '2022-08-13',
    pinned: false,
    visible: true,
    imported: true,
    importSource: 'italki',
  },
  {
    studentName: 'Donna Hu',
    teacherId: '',
    rating: 5,
    comment: "Jon is very responsible.",
    createdAt: '2022-08-11',
    pinned: false,
    visible: true,
    imported: true,
    importSource: 'italki',
  },
  {
    studentName: 'Ekaterina Strukova',
    teacherId: '',
    rating: 5,
    comment: "Great lesson as usually!",
    createdAt: '2022-08-05',
    pinned: false,
    visible: true,
    imported: true,
    importSource: 'italki',
  },
  {
    studentName: 'Donna Hu',
    teacherId: '',
    rating: 5,
    comment: "Jon always knows how to interest and guide my daughter.",
    createdAt: '2022-07-30',
    pinned: false,
    visible: true,
    imported: true,
    importSource: 'italki',
  },
  {
    studentName: 'Ekaterina Strukova',
    teacherId: '',
    rating: 5,
    comment: "Great lesson - fun and interesting for the kid!",
    createdAt: '2022-07-22',
    pinned: false,
    visible: true,
    imported: true,
    importSource: 'italki',
  },
  {
    studentName: 'Donna Hu',
    teacherId: '',
    rating: 5,
    comment: "Jon always knows how to interest my daughter in the class.",
    createdAt: '2022-07-14',
    pinned: false,
    visible: true,
    imported: true,
    importSource: 'italki',
  },
  {
    studentName: 'Donna Hu',
    teacherId: '',
    rating: 5,
    comment: "My daughter enjoyed Jon's class much.",
    createdAt: '2022-07-07',
    pinned: false,
    visible: true,
    imported: true,
    importSource: 'italki',
  },
  {
    studentName: 'Boo Boo W',
    teacherId: '',
    rating: 5,
    comment: "A good teacher having an interesting lesson",
    createdAt: '2022-07-03',
    pinned: false,
    visible: true,
    imported: true,
    importSource: 'italki',
  },
  {
    studentName: 'Donna Hu',
    teacherId: '',
    rating: 5,
    comment: "Jon is a great teacher.",
    createdAt: '2022-07-01',
    pinned: false,
    visible: true,
    imported: true,
    importSource: 'italki',
  },
  {
    studentName: 'Ekaterina Strukova',
    teacherId: '',
    rating: 5,
    comment: "Great style of communicating with kids! Easy and playful!",
    createdAt: '2022-06-29',
    pinned: false,
    visible: true,
    imported: true,
    importSource: 'italki',
    tags: ['For beginners'],
  },
  {
    studentName: 'Boo Boo W',
    teacherId: '',
    rating: 5,
    comment: "Jon is a good teacher.His lessons are very interesting.My kid likes his lessons",
    createdAt: '2022-06-28',
    pinned: false,
    visible: true,
    imported: true,
    importSource: 'italki',
  },
  {
    studentName: 'Donna Hu',
    teacherId: '',
    rating: 5,
    comment: "Jon is good at attracting my daughter's attention. Also he gives feedback and assigns homework after every class.",
    createdAt: '2022-06-26',
    pinned: false,
    visible: true,
    imported: true,
    importSource: 'italki',
  },
  {
    studentName: 'Catherina+Angelina',
    teacherId: '',
    rating: 5,
    comment: "Teacher Jon's lesson is very interesting,my twins loves the lesson.",
    createdAt: '2022-05-14',
    pinned: false,
    visible: true,
    imported: true,
    importSource: 'italki',
  },
  {
    studentName: 'Baymax',
    teacherId: '',
    rating: 5,
    comment: "Jon is really a professional and humorous teacher. Baymax loves his class a lot.",
    createdAt: '2022-04-11',
    pinned: false,
    visible: true,
    imported: true,
    importSource: 'italki',
  },
  {
    studentName: 'italki260368',
    teacherId: '',
    rating: 5,
    comment: "John老师在儿童英语教学上的方法很独特，孩子非常喜欢，以后就跟他学习啦",
    createdAt: '2022-04-10',
    pinned: false,
    visible: true,
    imported: true,
    importSource: 'italki',
    tags: ['For beginners'],
  },
  {
    studentName: 'Hugo Iris',
    teacherId: '',
    rating: 5,
    comment: "Hugo loved your class. We gonna book more lessons.",
    createdAt: '2022-03-03',
    pinned: false,
    visible: true,
    imported: true,
    importSource: 'italki',
  },
  {
    studentName: 'Ekaterina Strukova',
    teacherId: '',
    rating: 5,
    comment: "The lesson went great!",
    createdAt: '2022-02-11',
    pinned: false,
    visible: true,
    imported: true,
    importSource: 'italki',
  },
  {
    studentName: 'Elsa and Hannah',
    teacherId: '',
    rating: 5,
    comment: "Fantastic!",
    createdAt: '2022-02-09',
    pinned: false,
    visible: true,
    imported: true,
    importSource: 'italki',
  },
  {
    studentName: 'Carayang',
    teacherId: '',
    rating: 5,
    comment: "Jon is a good teacher who have made the class more interesting to get my son's attention. And he created the teaching contents by himself, which shows that he has his own ideas about teaching kids through his teaching experience all these years.",
    createdAt: '2022-02-06',
    pinned: false,
    visible: true,
    imported: true,
    importSource: 'italki',
    tags: ['Structured lessons'],
  },
  {
    studentName: 'Rui Duan',
    teacherId: '',
    rating: 5,
    comment: "Thank you for your patience",
    createdAt: '2021-12-18',
    pinned: false,
    visible: true,
    imported: true,
    importSource: 'italki',
  },
  {
    studentName: 'Mina',
    teacherId: '',
    rating: 5,
    comment: "The class is so fun. Thanks",
    createdAt: '2021-12-18',
    pinned: false,
    visible: true,
    imported: true,
    importSource: 'italki',
  },
  {
    studentName: 'Mina',
    teacherId: '',
    rating: 5,
    comment: "The class is So funny. My kid still a little timid to speaking. Hope joe help her feel more confident",
    createdAt: '2021-12-11',
    pinned: false,
    visible: true,
    imported: true,
    importSource: 'italki',
    tags: ['For beginners'],
  },
  {
    studentName: 'Rui Duan',
    teacherId: '',
    rating: 5,
    comment: "I like the teacher's teaching methods very much, but the network is a bit sluggish",
    createdAt: '2021-12-11',
    pinned: false,
    visible: true,
    imported: true,
    importSource: 'italki',
  },
  {
    studentName: 'Mina',
    teacherId: '',
    rating: 5,
    comment: "That's good try. Staring from English story books may arouse children's interest in english.",
    createdAt: '2021-12-04',
    pinned: false,
    visible: true,
    imported: true,
    importSource: 'italki',
  },
  {
    studentName: 'Mina',
    teacherId: '',
    rating: 5,
    comment: "Perfect for my kid. So much fun in these lessons",
    createdAt: '2021-11-27',
    pinned: false,
    visible: true,
    imported: true,
    importSource: 'italki',
    tags: ['For beginners'],
  },
  {
    studentName: 'Mina',
    teacherId: '',
    rating: 5,
    comment: "The kid learning so much fun here. Thanks to you.",
    createdAt: '2021-11-21',
    pinned: false,
    visible: true,
    imported: true,
    importSource: 'italki',
  },
  {
    studentName: 'Mina',
    teacherId: '',
    rating: 5,
    comment: "The class is very funny. My little girl can' wait for the next class.",
    createdAt: '2021-11-13',
    pinned: false,
    visible: true,
    imported: true,
    importSource: 'italki',
  },
  {
    studentName: 'Francesco',
    teacherId: '',
    rating: 5,
    comment: "Great lesson",
    createdAt: '2021-11-13',
    pinned: false,
    visible: true,
    imported: true,
    importSource: 'italki',
  },
  {
    studentName: 'Aleksandr Friman',
    teacherId: '',
    rating: 5,
    comment: "Thanks for the lesson",
    createdAt: '2017-01-14',
    pinned: false,
    visible: true,
    imported: true,
    importSource: 'italki',
  },
  {
    studentName: 'Francesco',
    teacherId: '',
    rating: 5,
    comment: "Great lesson",
    createdAt: '2013-06-12',
    pinned: false,
    visible: true,
    imported: true,
    importSource: 'italki',
  },
  {
    studentName: 'viktor.kolpak',
    teacherId: '',
    rating: 5,
    comment: "Hi, are we going to follow some book? It would be really good for me as I am old school student. thank you, thanks. viktor",
    createdAt: '2013-04-09',
    pinned: false,
    visible: true,
    imported: true,
    importSource: 'italki',
  },
  {
    studentName: 'Masatoshi',
    teacherId: '',
    rating: 5,
    comment: "Thank you for the session. It was fun talking to you.",
    createdAt: '2013-04-09',
    pinned: false,
    visible: true,
    imported: true,
    importSource: 'italki',
  },
];

export async function seedTeacherJonReviews(): Promise<number> {
  // Get teacher profile to get the ID
  const profile = await getTeacherProfileByUsername('teacherjon');
  
  if (!profile) {
    throw new Error('Teacher profile not found. Please seed the profile first.');
  }

  const teacherId = profile.id;
  
  // Check if reviews already exist
  const existingReviews = await getReviewsByTeacher(teacherId, false);
  if (existingReviews.length > 0) {
    console.log(`Found ${existingReviews.length} existing reviews. Skipping seed.`);
    return existingReviews.length;
  }

  // Create all reviews
  let count = 0;
  for (const review of italkiReviews) {
    await createReview({
      ...review,
      teacherId,
    });
    count++;
  }

  console.log(`Seeded ${count} reviews!`);
  return count;
}
